package org.tiatesting.gradle.plugin;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * Verifies the build generates the version resource the plugin reads.
 */
class TiaVersionTest {

    @Test
    void versionIsReadFromTheGeneratedResource() {
        // given - the resource generated by the build

        // when
        String version = TiaVersion.get();

        // then
        assertFalse(version.isEmpty());
    }
}
