package org.tiatesting.gradle.plugin;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Verifies the build generates the version resource the plugin reads.
 */
class TiaVersionTest {

    @Test
    void versionIsReadFromTheGeneratedResource() {
        // given - the resource generated by the build

        // when
        String version = TiaVersion.get();

        // then
        assertFalse(version.isEmpty());
    }

    @Test
    void slf4jVersionIsReadFromTheGeneratedResource() {
        // given - the resource generated by the build, from the build's slf4jVersion

        // when
        String version = TiaVersion.slf4j();

        // then
        assertTrue(version.matches("\\d+\\.\\d+.*"), version);
    }
}
