package org.tiatesting.core.persistence.dialect;

import org.junit.jupiter.api.Test;
import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.*;

class PostgresDialectTest {

    @Test
    void identityUsesGeneratedAsIdentity() {
        // given / when / then
        assertEquals("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                new PostgresDialect().identityColumnDefinition());
    }

    @Test
    void upsertUsesOnConflictDoUpdate() {
        // given
        PostgresDialect dialect = new PostgresDialect();
        // when
        String sql = dialect.upsert("tia_test_suite",
                Arrays.asList("name", "num_runs"), Arrays.asList("name"));
        // then
        assertEquals("INSERT INTO tia_test_suite (name, num_runs) VALUES (?, ?) "
                + "ON CONFLICT (name) DO UPDATE SET num_runs = EXCLUDED.num_runs", sql);
    }

    @Test
    void idIsPostgres() {
        // given / when / then
        assertEquals("postgres", new PostgresDialect().id());
    }

    @Test
    void schemaSql() {
        // given
        PostgresDialect d = new PostgresDialect();
        // when / then
        assertEquals("CREATE SCHEMA IF NOT EXISTS \"tia_main\"", d.createSchemaIfNotExistsSql("tia_main"));
        assertEquals("SET search_path TO \"tia_main\"", d.selectSchemaSql("tia_main"));
    }
}
