package org.tiatesting.core.persistence.dialect;

import org.junit.jupiter.api.Test;
import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.*;

class PostgresDialectTest {

    @Test
    void identityUsesGeneratedAsIdentity() {
        // given / when / then
        assertEquals("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                new PostgresDialect().identityColumnDefinition());
    }

    @Test
    void upsertUsesOnConflictDoUpdate() {
        // given
        PostgresDialect dialect = new PostgresDialect();
        // when
        String sql = dialect.upsert("tia_test_suite",
                Arrays.asList("name", "num_runs"), Arrays.asList("name"));
        // then
        assertEquals("INSERT INTO tia_test_suite (name, num_runs) VALUES (?, ?) "
                + "ON CONFLICT (name) DO UPDATE SET num_runs = EXCLUDED.num_runs", sql);
    }

    @Test
    void idIsPostgres() {
        // given / when / then
        assertEquals("postgres", new PostgresDialect().id());
    }

    @Test
    void clearTableTransactionallySqlUsesTruncateTable() {
        // given
        PostgresDialect dialect = new PostgresDialect();

        // when
        String sql = dialect.clearTableTransactionallySql("tia_source_method");

        // then
        assertEquals("TRUNCATE TABLE tia_source_method", sql);
    }

    @Test
    void schemaSql() {
        // given
        PostgresDialect d = new PostgresDialect();
        // when / then
        assertEquals("CREATE SCHEMA IF NOT EXISTS \"tia_main\"", d.createSchemaIfNotExistsSql("tia_main"));
        assertEquals("SET search_path TO \"tia_main\"", d.selectSchemaSql("tia_main"));
    }

    /**
     * Verifies that PostgresDialect returns BYTEA as the binary column type for variable-length
     * binary storage. Postgres has BYTEA but neither BLOB nor VARBINARY, so the dialect seam is
     * needed to abstract the difference from H2.
     */
    @Test
    void shouldUseByteaForBinaryColumns() {
        // given
        PostgresDialect dialect = new PostgresDialect();

        // when
        String type = dialect.binaryColumnType();

        // then
        assertEquals("BYTEA", type);
    }
}
