package org.tiatesting.core.persistence.dialect;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/** PostgreSQL dialect. SQL translations verified in the datastore viability spike. */
public final class PostgresDialect implements SqlDialect {

    /** {@inheritDoc} */
    @Override public String identityColumnDefinition() {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    /** {@inheritDoc} Postgres upsert via {@code INSERT ... ON CONFLICT (keys) DO UPDATE}. */
    @Override
    public String upsert(String table, List<String> columns, List<String> keyColumns) {
        StringBuilder ph = new StringBuilder();
        for (int i = 0; i < columns.size(); i++) { ph.append(i == 0 ? "?" : ", ?"); }
        List<String> updates = new ArrayList<>();
        for (String c : columns) {
            if (!keyColumns.contains(c)) { updates.add(c + " = EXCLUDED." + c); }
        }
        return "INSERT INTO " + table + " (" + String.join(", ", columns) + ") VALUES (" + ph + ") "
                + "ON CONFLICT (" + String.join(", ", keyColumns) + ") DO UPDATE SET "
                + String.join(", ", updates);
    }

    /** {@inheritDoc} Postgres folds unquoted identifiers to lower case. */
    @Override
    public boolean tableExists(Connection connection, String tableName) throws SQLException {
        try (ResultSet rs = connection.getMetaData()
                .getTables(null, null, tableName.toLowerCase(), new String[]{"TABLE"})) {
            return rs.next();
        }
    }

    /** {@inheritDoc} */
    @Override public String id() { return "postgres"; }
}
