package org.tiatesting.core.persistence.dialect;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/** PostgreSQL dialect. SQL translations verified in the datastore viability spike. */
public final class PostgresDialect implements SqlDialect {

    /** {@inheritDoc} */
    @Override public String identityColumnDefinition() {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    /** {@inheritDoc} Postgres uses {@code BYTEA}. */
    @Override public String binaryColumnType() { return "BYTEA"; }

    /** {@inheritDoc} Postgres upsert via {@code INSERT ... ON CONFLICT (keys) DO UPDATE}. */
    @Override
    public String upsert(String table, List<String> columns, List<String> keyColumns) {
        StringBuilder ph = new StringBuilder();
        for (int i = 0; i < columns.size(); i++) { ph.append(i == 0 ? "?" : ", ?"); }
        List<String> updates = new ArrayList<>();
        for (String c : columns) {
            if (!keyColumns.contains(c)) { updates.add(c + " = EXCLUDED." + c); }
        }
        return "INSERT INTO " + table + " (" + String.join(", ", columns) + ") VALUES (" + ph + ") "
                + "ON CONFLICT (" + String.join(", ", keyColumns) + ") DO UPDATE SET "
                + String.join(", ", updates);
    }

    /**
     * {@inheritDoc} Implemented as {@code TRUNCATE TABLE <table>}: unlike H2, Postgres's
     * {@code TRUNCATE} is transactional - it is safely rolled back if the enclosing transaction
     * does not commit - and it deallocates the table's pages in roughly constant time rather than
     * writing a per-row undo log entry the way {@code DELETE FROM} does, which matters for tables
     * that can hold hundreds of thousands of rows on the persist path.
     * @param table the table to clear
     * @return the {@code TRUNCATE TABLE} statement for the table
     */
    @Override public String clearTableTransactionallySql(String table) { return "TRUNCATE TABLE " + table; }

    /**
     * {@inheritDoc} Postgres folds unquoted identifiers to lower case, and preserves the case of a
     * quoted identifier (schema names here are always quoted and always lower case, since
     * {@code BranchSchema.schemaName} lower-cases them). The lookup is scoped to
     * {@link Connection#getSchema()} (the schema {@code JdbcDataStore.getConnection()} just
     * selected via {@code search_path}) via {@code DatabaseMetaData.getTables}, but
     * {@code schemaPattern} and {@code tableNamePattern} are JDBC LIKE patterns in which
     * {@code _} and {@code %} are wildcards - and every per-branch schema name is
     * {@code tia_<sanitised-branch>}, which always contains {@code _}. Passing the schema/table
     * name straight through as a pattern can therefore false-match a sibling schema (e.g. schema
     * {@code tia_v1_2} used as a pattern matches the literal schema {@code tia_v1x2}), wrongly
     * reporting a fresh branch schema as already migrated. To avoid that, the result set is
     * iterated and each row's {@code TABLE_SCHEM}/{@code TABLE_NAME} is checked for an exact
     * (non-pattern) match rather than trusting {@code rs.next()} from the pattern query.
     */
    @Override
    public boolean tableExists(Connection connection, String tableName) throws SQLException {
        String schema = connection.getSchema();
        String lowerTableName = tableName.toLowerCase();
        try (ResultSet rs = connection.getMetaData()
                .getTables(null, schema, lowerTableName, new String[]{"TABLE"})) {
            while (rs.next()) {
                if (schema.equals(rs.getString("TABLE_SCHEM")) && lowerTableName.equals(rs.getString("TABLE_NAME"))) {
                    return true;
                }
            }
        }
        return false;
    }

    /** {@inheritDoc} */
    @Override public String id() { return "postgres"; }

    @Override public String createSchemaIfNotExistsSql(String schema) {
        return "CREATE SCHEMA IF NOT EXISTS \"" + schema + "\"";
    }

    @Override public String selectSchemaSql(String schema) {
        return "SET search_path TO \"" + schema + "\"";
    }
}
