package org.tiatesting.core.persistence.dialect;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/** PostgreSQL dialect. SQL translations verified in the datastore viability spike. */
public final class PostgresDialect implements SqlDialect {

    /** {@inheritDoc} */
    @Override public String identityColumnDefinition() {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    /** {@inheritDoc} Postgres upsert via {@code INSERT ... ON CONFLICT (keys) DO UPDATE}. */
    @Override
    public String upsert(String table, List<String> columns, List<String> keyColumns) {
        StringBuilder ph = new StringBuilder();
        for (int i = 0; i < columns.size(); i++) { ph.append(i == 0 ? "?" : ", ?"); }
        List<String> updates = new ArrayList<>();
        for (String c : columns) {
            if (!keyColumns.contains(c)) { updates.add(c + " = EXCLUDED." + c); }
        }
        return "INSERT INTO " + table + " (" + String.join(", ", columns) + ") VALUES (" + ph + ") "
                + "ON CONFLICT (" + String.join(", ", keyColumns) + ") DO UPDATE SET "
                + String.join(", ", updates);
    }

    /**
     * {@inheritDoc} Postgres folds unquoted identifiers to lower case. The schema pattern is
     * scoped to {@link Connection#getSchema()} (the schema {@code JdbcDataStore.getConnection()}
     * just selected via {@code search_path}) rather than left as a wildcard: a {@code null} schema
     * pattern in {@code DatabaseMetaData.getTables} matches every schema in the catalog, so on a DB
     * shared by several per-branch schemas this would find another branch's tables and wrongly
     * report the current (possibly still-empty) branch schema as already migrated.
     */
    @Override
    public boolean tableExists(Connection connection, String tableName) throws SQLException {
        try (ResultSet rs = connection.getMetaData()
                .getTables(null, connection.getSchema(), tableName.toLowerCase(), new String[]{"TABLE"})) {
            return rs.next();
        }
    }

    /** {@inheritDoc} */
    @Override public String id() { return "postgres"; }

    @Override public String createSchemaIfNotExistsSql(String schema) {
        return "CREATE SCHEMA IF NOT EXISTS \"" + schema + "\"";
    }

    @Override public String selectSchemaSql(String schema) {
        return "SET search_path TO \"" + schema + "\"";
    }
}
